#!/usr/bin/env bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# force interactive mode
if [ ! -t 0 ]; then
    exec < /dev/tty
fi

# ask for confirmation
confirm() {
  read -p "$1 [y/N]: " response
  case "$response" in
    [yY][eE][sS]|[yY]) 
      true
      ;;
    *)
      false
      ;;
  esac
}

# get the commit type
get_commit_type() {
  echo "Select the type of commit" >&2
  select type in "chore" "fix" "feat"; do
    if [ -n "$type" ]; then
      echo "$type"
      break
    fi
  done
}

# get the ticket number (if any)
get_ticket_number() {
  if command -v task &> /dev/null; then
    TICKETS=$(task _unique ref)

    if [ -n "$TICKETS" ]; then
      echo "Select a reference ticket (or type to search):" >&2
      TICKET=$(echo "$TICKETS" | fzf --height 40% --reverse --print-query --prompt="Ticket: ")

      if [ -n "$TICKET" ]; then
        echo "$TICKET"
      else
        echo "No reference selected"
        exit 1
      fi
    else
      echo "No reference tickets found in tasks."
      exit 1
    fi
  else
    echo "Taskwarrior is not installed."
    exit 1
  fi
}

# main
if confirm "Do you want to do a conventional commit?"; then
  COMMIT_TYPE=$(get_commit_type)
  TICKET=$(get_ticket_number)
  if [ -n "$TICKET" ]; then
    ORIGINAL_MSG=$(cat "$COMMIT_MSG_FILE")
    NEW_MSG="$COMMIT_TYPE: $ORIGINAL_MSG, ref: $TICKET"
    echo "$NEW_MSG" > "$COMMIT_MSG_FILE"
  fi
fi




