#!/usr/bin/env bash
echo 'Setting up...'

if test ! $(which brew); then
  echo 'Installing homebrew...'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if test ! $(which nvim); then
  echo 'Installing nvim...'
  brew install neovim
  nvim --version
  # dependency to nvim
  brew install ripgrep

  touch $HOME/.profile.fish
  echo "set -g -x NVIMENV private" >> $HOME/.profile.fish
  echo "NVIMENV default is 'private', update .profile.fish if needed"
fi

